trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  displayName: 'Install Nodejs runtime'
  inputs:
    versionSpec: '10.x'

- script: |
    npm install
    npm run build
  displayName: 'Npm install and build'

- task: Docker@2
  displayName: 'Build and Push to Docker Registry'
  inputs:
    command: buildAndPush
    Dockerfile: Dockerfile
    buildContext : $(Build.Repository.LocalPath)
    containerRegistry: doDockerRegistry
    repository: fabrikregistry/fabrikadminportal
    tags: latest